version: "3"
services:
  backend:
    image: ppodds/ncuplus-backend:latest
    restart: always
    volumes:
      - ./backend/uploads:/home/node/app/uploads
    env_file:
      - ./backend/.env
    environment:
      - TZ=Asia/Taipei
  frontend:
    image: ppodds/ncuplus-frontend:latest
    restart: always
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    environment:
      - TZ=Asia/Taipei
  nginx:
    build:
      context: "./nginx"
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Asia/Taipei
