version: "3"
services:
  backend:
    image: ppodds/ncuplus-backend:latest
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
  frontend:
    image: ppodds/ncuplus-frontend:latest
    restart: always
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    ports:
      - 3001:3000
  nginx:
    build:
      context: "./nginx"
    restart: always
    volumes:
      - /var/www/_letsencrypt:/var/www/_letsencrypt
